import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { initServerI18next, getT, getResources, generateI18nStaticParams } from 'next-i18next/server'
import { I18nProvider } from 'next-i18next/client'
import i18nConfig from '../i18n.config'
import Header from "@/components/Header";
import Warning from "@/components/Warning";
import Places, { Place } from "./PlaceContext";


initServerI18next(i18nConfig)

export async function generateStaticParams() {
  return generateI18nStaticParams()
}

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>
}>) {
  const { lng } = await params
  const { i18n } = await getT()
  const resources = getResources(i18n)
  const placesRes = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/places`, {
    cache: 'no-store' 
  })
  const places: Place[] = await (placesRes.json() as Promise<Place[]>)
  console.log(places)
  return (
    <html
      lang={lng}
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <I18nProvider  language={lng} resources={resources}>
        <Header />
        <Warning />
        <Places value={[...places]}>
             {children}
        </Places>
        </I18nProvider>
        </body>
        
    </html>
  );
}
